<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class BooksTableSeeder extends Seeder
{

    public function run(): void
    {
        DB::table('books')->insert([
            [
                'book_name' => 'Sokrates’in Savunmasi',
                'author' => 'Platon',
                'description' => 'Platon (MÖ yaklaşık 428-MÖ yaklaşık 348): Bugünkü üniversitenin atası sayılan Akademia’nın kurucusu ve hocası Sokrates’i konuşturduğu diyaloglarla felsefeyi yazıya en iyi aktarmış ustalardan biridir. Bu kitapta birbirini tamamlayan dört diyalog yer almaktadır. İlk diyalog olan Euthyphron da yargılanışının öncesi anlatılır ve dinsizlikle suçlanan Sokrates’in inançları hakkında bilgi verilir. Sokrates’in Savunması’nda ise yargı süreci anlatılmaktadır. Kriton’da hüküm sonrası anlatılır, bir yurttaşın saygı duyması gereken ilkeler tartışılır. Platon’un en şiirsel eserlerinden biri olan Phaidon daysa Sokrates’in son günü anlatılırken ruh hakkındaki düşünceleri yansıtılmaktadır.',
                'isbn_number' => '978-605-360-070-2',
                'number_of_pages' => 206,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'book_name' => 'Yabanci',
                'author' => 'Albet Camus',
                'description' => '1942’de yayımlanan Yabancı, romancı, tiyatro yazarı ve düşünür olarak İkinci Dünya Savaşı’ndan sonra yalnız Fransa’da değil tüm dünyada kuşağının sözcüsü ve yol göstericisi olarak kabul edilen Albert Camus’nün, ilk ve en çok ses getiren yapıtıdır.',
                'isbn_number' => '978-975-510-586-4',
                'number_of_pages' => 111,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'book_name' => 'Savaş ve Barış',
                'author' => 'Lev Tolstoy',
                'description' => 'Savaş ve Barış, Tolstoy’un başyapıtı olup, Rus toplumunun Napolyon Savaşları dönemindeki sosyo-politik yapısını anlatan kapsamlı bir romandır.',
                'isbn_number' => '978-045-152-288-4',
                'number_of_pages' => 1225,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'book_name' => 'Suç ve Ceza',
                'author' => 'Fyodor Dostoyevski',
                'description' => 'Suç ve Ceza, Dostoyevski’nin en önemli romanlarından biri olup, bir genç üniversite öğrencisinin işlediği cinayet ve sonrasındaki vicdan azabı üzerinden insan ruhunu derinlemesine inceler.',
                'isbn_number' => '978-014-044-913-6',
                'number_of_pages' => 430,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'book_name' => 'Gülün Adı',
                'author' => 'Umberto Eco',
                'description' => 'Gülün Adı, Orta Çağ’daki bir manastırda geçen cinayetleri araştıran bir rahibin hikayesini anlatan ve tarih, felsefe ve edebiyatı harmanlayan bir romandır.',
                'isbn_number' => '978-015-600-131-1',
                'number_of_pages' => 500,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'book_name' => 'Bülbülü Öldürmek',
                'author' => 'Harper Lee',
                'description' => 'Bülbülü Öldürmek, Amerikan Güneyi’nde bir çocuk olarak büyüyen Scout Finch’in, ırkçılıkla ve adaletsizlikle mücadele eden babasının yanında gelişen olayları anlatır.',
                'isbn_number' => '978-006-112-008-4',
                'number_of_pages' => 281,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'book_name' => '1984',
                'author' => 'George Orwell',
                'description' => '1984, totaliter bir rejim altında yaşayan bir adamın öyküsünü anlatan distopik bir romandır. Orwell’in gelecekteki toplumsal ve politik tehlikeler üzerine yaptığı derin bir uyarıdır.',
                'isbn_number' => '978-045-152-493-2',
                'number_of_pages' => 328,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'book_name' => 'Kayıp Zamanın İzinde',
                'author' => 'Marcel Proust',
                'description' => 'Kayıp Zamanın İzinde, zamanın ve hafızanın insan hayatı üzerindeki etkilerini inceleyen uzun bir romandır ve Proust’un başyapıtıdır.',
                'isbn_number' => '978-037-575-154-7',
                'number_of_pages' => 4216,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'book_name' => 'Sineklerin Tanrısı',
                'author' => 'William Golding',
                'description' => 'Sineklerin Tanrısı, bir grup çocuğun ıssız bir adada yaşadıkları korkunç olayları ve insan doğasının karanlık yönlerini araştıran bir romandır.',
                'isbn_number' => '978-039-950-148-7',
                'number_of_pages' => 224,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'book_name' => 'Kürk Mantolu Madonna',
                'author' => 'Sabahattin Ali',
                'description' => 'Kürk Mantolu Madonna, bir adamın hayatının dönüm noktası olan ve ona gerçek aşkı tanıtan bir kadınla olan ilişkisini anlatan bir romandır.',
                'isbn_number' => '978-975-08-0446-6',
                'number_of_pages' => 160,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'book_name' => 'Anna Karenina',
                'author' => 'Lev Tolstoy',
                'description' => 'Anna Karenina, Rus toplumu içinde cinsel ve sosyal ilişkilerin nasıl değiştiğini ve insanların bu ilişkilerde nasıl mücadele ettiğini anlatan bir romandır.',
                'isbn_number' => '978-014-303-500-8',
                'number_of_pages' => 864,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'book_name' => 'Küçük Prens',
                'author' => 'Antoine de Saint-Exupéry',
                'description' => 'Küçük Prens, evreni keşfetmeye çıkan küçük bir prensin yolculukları sırasında karşılaştığı karakterler ve yaşadığı maceraları anlatan bir masaldır.',
                'isbn_number' => '978-015-601-398-4',
                'number_of_pages' => 96,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'book_name' => 'Yüzüklerin Efendisi: Yüzük Kardeşliği',
                'author' => 'J.R.R. Tolkien',
                'description' => 'Yüzüklerin Efendisi serisinin ilk kitabı olan Yüzük Kardeşliği, Orta Dünya’daki kötülüğe karşı verilen savaşın ilk adımlarını ve karakterlerin maceralarını anlatır.',
                'isbn_number' => '978-039-548-931-4',
                'number_of_pages' => 423,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'book_name' => 'Sefiller',
                'author' => 'Victor Hugo',
                'description' => 'Sefiller, Fransız Devrimi sonrası sosyal adaletsizliklerin ve bireysel mücadelelerin anlatıldığı epik bir romandır.',
                'isbn_number' => '978-045-141-943-9',
                'number_of_pages' => 1232,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'book_name' => 'İstanbul Hatırası',
                'author' => 'Ahmet Ümit',
                'description' => 'İstanbul Hatırası, bir cinayet soruşturması etrafında gelişen olayları ve İstanbul’un tarihi dokusunu derinlemesine keşfeden bir polisiye romandır.',
                'isbn_number' => '978-975-07-2715-4',
                'number_of_pages' => 368,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'book_name' => 'Büyücü',
                'author' => 'John Fowles',
                'description' => 'Büyücü, genç bir adamın egzotik bir adada yaşadığı tuhaf ve gizemli olayları anlatan bir romandır.',
                'isbn_number' => '978-031-629-116-5',
                'number_of_pages' => 448,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'book_name' => 'Karamazov Kardeşler',
                'author' => 'Fyodor Dostoyevski',
                'description' => 'Karamazov Kardeşler, bir ailenin içsel çatışmalarını ve ahlaki sorgulamalarını derinlemesine inceleyen kapsamlı bir romandır.',
                'isbn_number' => '978-037-452-837-9',
                'number_of_pages' => 796,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'book_name' => 'Savaşın Çocukları',
                'author' => 'E. M. Forster',
                'description' => 'Savaşın Çocukları, savaşın insanlar üzerindeki etkilerini ve toplumsal değişimleri ele alan bir romandır.',
                'isbn_number' => '978-015-618-998-8',
                'number_of_pages' => 384,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'book_name' => 'Mülksüzler',
                'author' => 'Ursula K. Le Guin',
                'description' => 'Mülksüzler, ütopik bir gezegende geçen ve toplumsal sistemlerin eleştirisini yapan bir bilim kurgu romanıdır.',
                'isbn_number' => '978-044-101-970-1',
                'number_of_pages' => 320,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'book_name' => 'Kırmızı ve Siyah',
                'author' => 'Stendhal',
                'description' => 'Kırmızı ve Siyah, 19. yüzyıl Fransız toplumunda sosyal hırs ve kişisel çatışmaların öyküsünü anlatan bir romandır.',
                'isbn_number' => '978-014-044-014-0',
                'number_of_pages' => 576,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'book_name' => 'Karanlıkta Dans',
                'author' => 'Anne Rice',
                'description' => 'Karanlıkta Dans, vampir temalı bir fantastik kurgu romanı olup, bir vampir toplumunun iç çatışmalarını ve bireysel hikayeleri keşfeder.',
                'isbn_number' => '978-034-533-766-5',
                'number_of_pages' => 432,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'book_name' => 'Gündüzün Karanlığı',
                'author' => 'F. Scott Fitzgerald',
                'description' => 'Gündüzün Karanlığı, Amerikan toplumunun üst sınıfının boşluğunu ve ahlaki çöküşünü detaylandıran bir romandır.',
                'isbn_number' => '978-074-327-356-5',
                'number_of_pages' => 180,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'book_name' => 'Sahilde Kafka',
                'author' => 'Haruki Murakami',
                'description' => 'Sahilde Kafka, gerçek ve hayal dünyası arasında gidip gelen bir gencin ve yaşlı bir adamın yollarının kesiştiği sürükleyici bir roman.',
                'isbn_number' => '978-030-738-643-0',
                'number_of_pages' => 496,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'book_name' => 'İçimizdeki Şeytan',
                'author' => 'Ayfer Tunç',
                'description' => 'İçimizdeki Şeytan, modern toplumda bireylerin içsel çatışmalarını ve toplumsal sorunlarını irdeleyen bir eserdir.',
                'isbn_number' => '978-975-08-2513-5',
                'number_of_pages' => 400,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'book_name' => 'Köpekler Adası',
                'author' => 'J.K. Rowling',
                'description' => 'Köpekler Adası, gizemli bir adada köpeklerle ilgili fantastik bir macerayı anlatan çocuklar ve gençler için yazılmış bir romandır.',
                'isbn_number' => '978-054-501-022-1',
                'number_of_pages' => 300,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'book_name' => 'Kötü Kızlar',
                'author' => 'Liane Moriarty',
                'description' => 'Kötü Kızlar, dört kadının karmaşık ilişkilerini ve aralarındaki çatışmaları ele alan bir çağdaş roman.',
                'isbn_number' => '978-125-006-983-4',
                'number_of_pages' => 384,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'book_name' => 'Zamanın Kızı',
                'author' => 'Diana Gabaldon',
                'description' => 'Zamanın Kızı, zaman yolculuğu ve tarihsel bir aşk hikayesini bir araya getiren bir tarihi kurgu romanıdır.',
                'isbn_number' => '978-038-530-230-6',
                'number_of_pages' => 880,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'book_name' => 'Dünyanın Sonundaki Ev',
                'author' => 'Kurt Vonnegut',
                'description' => 'Dünyanın Sonundaki Ev, modern dünyadaki absürd olayları ve insan ilişkilerini hicveden bir bilim kurgu romanıdır.',
                'isbn_number' => '978-038-533-326-0',
                'number_of_pages' => 240,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'book_name' => 'Cehennem',
                'author' => 'Dan Brown',
                'description' => 'Cehennem, semboller ve şifreler üzerine kurulu bir cinayet soruşturması etrafında gelişen bir gerilim romanıdır.',
                'isbn_number' => '978-038-553-785-8',
                'number_of_pages' => 480,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'book_name' => 'Yıldızların Altında',
                'author' => 'John Green',
                'description' => 'Yıldızların Altında, kanser hastası iki gencin hayatı ve aşkı üzerine odaklanan duygusal bir gençlik romanıdır.',
                'isbn_number' => '978-052-547-881-2',
                'number_of_pages' => 313,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'book_name' => 'Doğu Ekspresinde Cinayet',
                'author' => 'Agatha Christie',
                'description' => 'Doğu Ekspresinde Cinayet, bir tren yolculuğunda işlenen cinayet ve bu cinayetle ilgili çözülmeye çalışılan gizemli olayları anlatan bir polisiye romandır.',
                'isbn_number' => '978-006-207-350-1',
                'number_of_pages' => 256,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'book_name' => 'Gözyaşları ve Gülümsemeler',
                'author' => 'Paulo Coelho',
                'description' => 'Gözyaşları ve Gülümsemeler, yaşamın zorlukları ve kişisel gelişim üzerine odaklanan dokunaklı bir romandır.',
                'isbn_number' => '978-006-059-536-2',
                'number_of_pages' => 288,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'book_name' => 'Gözyaşları ve Gülümsemeler',
                'author' => 'Paulo Coelho',
                'description' => 'Gözyaşları ve Gülümsemeler, yaşamın zorlukları ve kişisel gelişim üzerine odaklanan dokunaklı bir romandır.',
                'isbn_number' => '978-006-059-536-2',
                'number_of_pages' => 288,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'book_name' => 'Zamanın Çeyrek Yüzyılı',
                'author' => 'Margaret Atwood',
                'description' => 'Zamanın Çeyrek Yüzyılı, yakın gelecekteki distopik bir dünyada geçen ve insan doğasının değişimini sorgulayan bir bilim kurgu romanıdır.',
                'isbn_number' => '978-006-059-536-2',
                'number_of_pages' => 320,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'book_name' => 'Denizin Altında',
                'author' => 'Jules Verne',
                'description' => 'Denizin Altında, bir denizaltının keşif yolculuklarını ve bu süreçte yaşanan maceraları anlatan klasik bir bilim kurgu romanıdır.',
                'isbn_number' => '978-006-059-536-2',
                'number_of_pages' => 342,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'book_name' => 'Aşk ve Gurur',
                'author' => 'Jane Austen',
                'description' => 'Aşk ve Gurur, İngiliz toplumunda aşk, sınıf ve kişisel gelişim üzerine yoğunlaşan bir klasik romandır.',
                'isbn_number' => '978-006-059-536-2',
                'number_of_pages' => 432,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'book_name' => 'Sonsuzluk Savaşçıları',
                'author' => 'Isaac Asimov',
                'description' => 'Sonsuzluk Savaşçıları, galaksiler arası savaşlar ve uygarlıklar arasındaki çatışmalar üzerine kurulu bir bilim kurgu romanıdır.',
                'isbn_number' => '978-006-059-536-2',
                'number_of_pages' => 416,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'book_name' => 'Karanlık Zihinler',
                'author' => 'Alexandra Bracken',
                'description' => 'Karanlık Zihinler, gelecekteki bir dünyada, gençlerin sahip olduğu özel güçlerle mücadele eden bir grubun hikayesini anlatan bir distopyadır.',
                'isbn_number' => '978-006-059-536-2',
                'number_of_pages' => 496,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'book_name' => 'Kayıp Yüzyılın Prensesi',
                'author' => 'Nina George',
                'description' => 'Kayıp Yüzyılın Prensesi, tarihi bir gizem ve aşk hikayesini bir araya getiren etkileyici bir romandır.',
                'isbn_number' => '978-006-059-536-2',
                'number_of_pages' => 408,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'book_name' => 'Gece Yalanları',
                'author' => 'John Verdon',
                'description' => 'Gece Yalanları, çözülmesi zor bir cinayet soruşturması etrafında gelişen bir gerilim romanıdır.',
                'isbn_number' => '978-006-059-536-2',
                'number_of_pages' => 384,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'book_name' => 'Rüzgarın Şarkısı',
                'author' => 'Khaled Hosseini',
                'description' => 'Rüzgarın Şarkısı, savaşın ve aşkın etkilerini derinlemesine işleyen, etkileyici bir hikayeye sahip bir romandır.',
                'isbn_number' => '978-006-059-536-2',
                'number_of_pages' => 371,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'book_name' => 'Seni Hiç Unutmadım',
                'author' => 'Nicolas Sparks',
                'description' => 'Seni Hiç Unutmadım, geçmişin ve kaybedilen aşkın etkilerini ele alan, dokunaklı bir romantik dramadır.',
                'isbn_number' => '978-006-059-536-2',
                'number_of_pages' => 355,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'book_name' => 'Mürekkep Yürek',
                'author' => 'Cornelia Funke',
                'description' => 'Mürekkep Yürek, bir kitap karakterinin gerçek dünyaya geçişi ve bu durumun yaratacağı karmaşayı anlatan bir fantastik maceradır.',
                'isbn_number' => '978-006-059-536-2',
                'number_of_pages' => 534,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'book_name' => 'Hikayenin Sonu',
                'author' => 'Jonathan Franzen',
                'description' => 'Hikayenin Sonu, modern Amerikan hayatının karmaşasını ve bireylerin birbirleriyle olan ilişkilerini anlatan bir romandır.',
                'isbn_number' => '978-006-059-536-2',
                'number_of_pages' => 562,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'book_name' => 'Kuşlar ve Çiçekler',
                'author' => 'Yoshimoto Banana',
                'description' => 'Kuşlar ve Çiçekler, Japon yazar Yoshimoto Banana’nın yaşam, aşk ve kayıp temalarını işlediği bir romandır.',
                'isbn_number' => '978-006-059-536-2',
                'number_of_pages' => 208,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'book_name' => 'Gölge ve Kemik',
                'author' => 'Leigh Bardugo',
                'description' => 'Gölge ve Kemik, büyü ve savaşla dolu bir dünyada geçen fantastik bir macerayı anlatan genç yetişkin romanıdır.',
                'isbn_number' => '978-006-059-536-2',
                'number_of_pages' => 368,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'book_name' => 'Mavi Ay',
                'author' => 'Alice Hoffman',
                'description' => 'Mavi Ay, ailesinin ve geçmişinin etkisi altında kalan bir kadının büyüme ve kendini bulma hikayesini anlatır.',
                'isbn_number' => '978-006-059-536-2',
                'number_of_pages' => 296,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'book_name' => 'Savaşın Dişi',
                'author' => 'Pat Barker',
                'description' => 'Savaşın Dişi, Birinci Dünya Savaşı’nın etkilerini ve savaşın cinsiyet rollerine etkilerini keşfeden bir romandır.',
                'isbn_number' => '978-006-059-536-2',
                'number_of_pages' => 256,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'book_name' => 'Gölgedeki Çocuklar',
                'author' => 'Shirley Jackson',
                'description' => 'Gölgedeki Çocuklar, ürkütücü ve gerilim dolu bir hikaye ile çocukların dünyasında gizemli olayları konu alır.',
                'isbn_number' => '978-006-059-536-2',
                'number_of_pages' => 352,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'book_name' => 'Kırık Kalper Kulübü',
                'author' => 'Jennifer Weiner',
                'description' => 'Kırık Kalper Kulübü, hayatın zorlukları ve kişisel mücadeleler üzerinden arkadaşlık ve aşk temasını işleyen bir romandır.',
                'isbn_number' => '978-006-059-536-2',
                'number_of_pages' => 400,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'book_name' => 'Karanlık Ev',
                'author' => 'Harlan Coben',
                'description' => 'Karanlık Ev, bir cinayet soruşturması ve bu soruşturmanın etrafında gelişen gizemli olayları anlatan gerilim romanıdır.',
                'isbn_number' => '978-006-059-536-2',
                'number_of_pages' => 432,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'book_name' => 'Kayıp Şehir',
                'author' => 'Carlos Ruiz Zafón',
                'description' => 'Kayıp Şehir, Barcelona’da geçen ve kaybolmuş bir kitabın izini süren bir genç adamın hikayesini anlatan romanıdır.',
                'isbn_number' => '978-006-059-536-2',
                'number_of_pages' => 464,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'book_name' => 'Üçüncü Kız',
                'author' => 'Agatha Christie',
                'description' => 'Üçüncü Kız, ünlü dedektif Hercule Poirot’nun bir cinayet soruşturmasını ve bu soruşturmadaki karmaşıklıkları çözmesini konu alır.',
                'isbn_number' => '978-006-059-536-2',
                'number_of_pages' => 224,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'book_name' => 'Son Akşam Yemeği',
                'author' => 'Dan Brown',
                'description' => 'Son Akşam Yemeği, tarihi ve sanatsal bir gizemi çözmeye çalışan bir profesörün hikayesini anlatan gerilim romanıdır.',
                'isbn_number' => '978-006-059-536-2',
                'number_of_pages' => 454,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'book_name' => 'Seni Unutmak',
                'author' => 'Liane Moriarty',
                'description' => 'Seni Unutmak, geçmişin etkilerini ve kişisel ilişkilerin karmaşıklığını inceleyen bir romantik dramadır.',
                'isbn_number' => '978-006-059-536-2',
                'number_of_pages' => 384,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'book_name' => 'Görünmeyen Kadın',
                'author' => 'Paula Hawkins',
                'description' => 'Görünmeyen Kadın, bir kadın cinayetinin etrafında gelişen olayları ve bu olayların karakterler üzerindeki etkilerini anlatır.',
                'isbn_number' => '978-006-059-536-2',
                'number_of_pages' => 336,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'book_name' => 'Gece Yolu',
                'author' => 'Michael Connelly',
                'description' => 'Gece Yolu, bir cinayet soruşturmasını ve bu süreçte yaşanan gerilimli olayları anlatan bir polisiye romanıdır.',
                'isbn_number' => '978-006-059-536-2',
                'number_of_pages' => 416,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'book_name' => 'Karanlıkta Bir Işık',
                'author' => 'Celeste Ng',
                'description' => 'Karanlıkta Bir Işık, aile içi ilişkiler ve kişisel sırlar etrafında gelişen bir dramadır.',
                'isbn_number' => '978-006-059-536-2',
                'number_of_pages' => 320,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'book_name' => 'Mükemmel Suç',
                'author' => 'Gillian Flynn',
                'description' => 'Mükemmel Suç, bir cinayetin arkasındaki sırları ve bu olayın karakterler üzerindeki etkilerini araştıran bir gerilim romanıdır.',
                'isbn_number' => '978-006-059-536-2',
                'number_of_pages' => 422,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'book_name' => 'Yüzeyin Altında',
                'author' => 'Jonathan Franzen',
                'description' => 'Yüzeyin Altında, modern Amerikan toplumunun karmaşıklığını ve bireylerin hayatlarındaki mücadeleleri derinlemesine inceler.',
                'isbn_number' => '978-006-059-536-2',
                'number_of_pages' => 592,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'book_name' => 'Sonsuz Karar',
                'author' => 'Lisa Jewell',
                'description' => 'Sonsuz Karar, kişisel seçimlerin ve geçmişin bir insanın hayatındaki etkilerini araştıran bir dramadır.',
                'isbn_number' => '978-006-059-536-2',
                'number_of_pages' => 384,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'book_name' => 'Kayıp Çocuk',
                'author' => 'Jodi Picoult',
                'description' => 'Kayıp Çocuk, bir çocuğun kaybolması ve bunun aile üzerindeki etkilerini konu alan bir dramatik gerilim romanıdır.',
                'isbn_number' => '978-006-059-536-2',
                'number_of_pages' => 416,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'book_name' => 'Gizemli Günler',
                'author' => 'Tana French',
                'description' => 'Gizemli Günler, geçmişin izlerini ve bir cinayet soruşturmasının iç yüzünü araştıran bir suç romanıdır.',
                'isbn_number' => '978-006-059-536-2',
                'number_of_pages' => 448,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'book_name' => 'Nefes Nefese',
                'author' => 'Sylvia Day',
                'description' => 'Nefes Nefese, tutkulu bir aşk hikayesini ve bunun karakterler üzerindeki etkilerini anlatan bir romantik dramadır.',
                'isbn_number' => '978-006-059-536-2',
                'number_of_pages' => 368,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'book_name' => 'Sonbahar Melankolisi',
                'author' => 'Albert Camus',
                'description' => 'Sonbahar Melankolisi, bireylerin içsel dünyasını ve toplumsal izolasyonlarını ele alan bir roman.',
                'isbn_number' => '978-006-059-536-2',
                'number_of_pages' => 272,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'book_name' => 'Beni Hiç Unutma',
                'author' => 'Jojo Moyes',
                'description' => 'Beni Hiç Unutma, aşkın ve kaybın izlerini takip eden, dokunaklı bir romantik dramadır.',
                'isbn_number' => '978-006-059-536-2',
                'number_of_pages' => 416,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'book_name' => 'Arka Sokak',
                'author' => 'P.D. James',
                'description' => 'Arka Sokak, bir cinayet soruşturmasını ve bu soruşturmanın arka planındaki karmaşıklıkları detaylandıran bir polisiye romandır.',
                'isbn_number' => '978-006-059-536-2',
                'number_of_pages' => 336,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'book_name' => 'Gündüzün Yüzü',
                'author' => 'Margaret Atwood',
                'description' => 'Gündüzün Yüzü, modern yaşamın zorluklarını ve bireylerin bu zorluklarla başa çıkma yollarını anlatan bir romandır.',
                'isbn_number' => '978-006-059-536-2',
                'number_of_pages' => 304,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'book_name' => 'Ayrılığın Eşiğinde',
                'author' => 'Colleen Hoover',
                'description' => 'Ayrılığın Eşiğinde, bir ilişkideki zorlukları ve kişisel seçimlerin sonuçlarını derinlemesine inceleyen bir dramadır.',
                'isbn_number' => '978-006-059-536-2',
                'number_of_pages' => 370,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'book_name' => 'Sonsuz Gün',
                'author' => 'Khaled Hosseini',
                'description' => 'Sonsuz Gün, bir ailenin ve onların geçmişinin etkisiyle yüzleşme süreçlerini anlatan bir roman.',
                'isbn_number' => '978-006-059-536-2',
                'number_of_pages' => 386,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'book_name' => 'Kayıp Kız',
                'author' => 'Tess Gerritsen',
                'description' => 'Kayıp Kız, bir kızın kaybolması ve ardından ortaya çıkan gizemli olayları anlatan bir gerilim romanıdır.',
                'isbn_number' => '978-006-059-536-2',
                'number_of_pages' => 336,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'book_name' => 'Gölge Yolu',
                'author' => 'Maya Angelou',
                'description' => 'Gölge Yolu, bir kadının kendi kimliğini bulma yolundaki mücadelelerini ve yaşamını konu alır.',
                'isbn_number' => '978-006-059-536-2',
                'number_of_pages' => 258,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'book_name' => 'Bir Gün Daha',
                'author' => 'Marc Levy',
                'description' => 'Bir Gün Daha, kaybolmuş bir aşkı ve geçmişin izlerini araştıran duygusal bir hikaye sunar.',
                'isbn_number' => '978-006-059-536-2',
                'number_of_pages' => 300,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'book_name' => 'Karanlıkta Sırlar',
                'author' => 'Harlan Coben',
                'description' => 'Karanlıkta Sırlar, geçmişteki bir cinayet ve bunun günümüzdeki etkilerini araştıran bir gerilim romanıdır.',
                'isbn_number' => '978-006-059-536-2',
                'number_of_pages' => 392,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'book_name' => 'Mürekkep Yürek',
                'author' => 'Cornelia Funke',
                'description' => 'Mürekkep Yürek, bir kitabın gerçek dünyaya geçişi ve bunun getirdiği maceraları konu alır.',
                'isbn_number' => '978-006-059-536-2',
                'number_of_pages' => 540,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'book_name' => 'Yalnız Yıldızlar',
                'author' => 'John Green',
                'description' => 'Yalnız Yıldızlar, genç aşıkların zorluklar ve yaşam koşulları arasında birbirlerine olan bağlılıklarını anlatır.',
                'isbn_number' => '978-006-059-536-2',
                'number_of_pages' => 336,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'book_name' => 'Bir Sonbahar Günü',
                'author' => 'Anita Shreve',
                'description' => 'Bir Sonbahar Günü, bir kadının hayatındaki önemli değişiklikleri ve bunların onun üzerinde yarattığı etkileri konu alır.',
                'isbn_number' => '978-006-059-536-2',
                'number_of_pages' => 340,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'book_name' => 'Aşkın Sözleri',
                'author' => 'Jojo Moyes',
                'description' => 'Aşkın Sözleri, iki kişinin yaşamları arasındaki aşkı ve bunun getirdiği zorlukları ele alır.',
                'isbn_number' => '978-006-059-536-2',
                'number_of_pages' => 368,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'book_name' => 'Geceyi Kucaklamak',
                'author' => 'Deborah Harkness',
                'description' => 'Geceyi Kucaklamak, bir kadının zaman yolculuğu ve büyü dolu bir dünyadaki maceralarını anlatır.',
                'isbn_number' => '978-006-059-536-2',
                'number_of_pages' => 512,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'book_name' => 'Denizin Derinliklerinde',
                'author' => 'Maggie Shipstead',
                'description' => 'Denizin Derinliklerinde, bir deniz yolculuğunda yaşanan olaylar ve kişisel keşifler üzerine yazılmış bir romandır.',
                'isbn_number' => '978-006-059-536-2',
                'number_of_pages' => 444,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'book_name' => 'Sessiz Şehir',
                'author' => 'S.J. Watson',
                'description' => 'Sessiz Şehir, hafıza kaybı yaşayan bir kadının geçmişini ve gerçekleri yeniden keşfetme mücadelesini konu alır.',
                'isbn_number' => '978-006-059-536-2',
                'number_of_pages' => 416,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'book_name' => 'Büyülü Ev',
                'author' => 'Alice Hoffman',
                'description' => 'Büyülü Ev, bir ailenin kuşaklar boyunca devam eden sırlarını ve onları etkileyen mistik olayları anlatır.',
                'isbn_number' => '978-006-059-536-2',
                'number_of_pages' => 384,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'book_name' => 'Karanlık Yüzler',
                'author' => 'Robert Galbraith',
                'description' => 'Karanlık Yüzler, bir dedektifin karmaşık bir cinayet soruşturmasını ve bu süreçte karşılaştığı engelleri anlatan bir gerilim romanıdır.',
                'isbn_number' => '978-006-059-536-2',
                'number_of_pages' => 416,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'book_name' => 'Gözyaşı Kralı',
                'author' => 'Melina Marchetta',
                'description' => 'Gözyaşı Kralı, karmaşık bir aile dramı ve bireysel mücadelelerin anlatıldığı etkileyici bir hikaye.',
                'isbn_number' => '978-006-059-536-2',
                'number_of_pages' => 340,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'book_name' => 'Düşler Ülkesi',
                'author' => 'Philip K. Dick',
                'description' => 'Düşler Ülkesi, bilim kurgu ve felsefi sorgulamalarla dolu, gerçeklik ve hayalin sınırlarını zorlayan bir roman.',
                'isbn_number' => '978-006-059-536-2',
                'number_of_pages' => 288,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'book_name' => 'Gizli Aşk',
                'author' => 'Nicolas Sparks',
                'description' => 'Gizli Aşk, romantizmin ve kalp kırıklığının iç içe geçtiği, duygusal bir aşk hikayesi sunar.',
                'isbn_number' => '978-006-059-536-2',
                'number_of_pages' => 352,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'book_name' => 'Yıldızlı Gece',
                'author' => 'Eleanor Oliphant',
                'description' => 'Yıldızlı Gece, kişisel iyileşme ve toplumsal bağlar etrafında gelişen, umut verici bir hikaye.',
                'isbn_number' => '978-006-059-536-2',
                'number_of_pages' => 370,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'book_name' => 'İçsel Fırtına',
                'author' => 'Joan Didion',
                'description' => 'İçsel Fırtına, bir kadının içsel dünyasını ve kişisel krizlerini keşfeden, edebi bir başyapıt.',
                'isbn_number' => '978-006-059-536-2',
                'number_of_pages' => 288,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'book_name' => 'Gökyüzü Yolu',
                'author' => 'Stephen King',
                'description' => 'Gökyüzü Yolu, korku ve gerilim unsurlarıyla dolu, unutulmaz bir hikaye sunar.',
                'isbn_number' => '978-006-059-536-2',
                'number_of_pages' => 450,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'book_name' => 'Deniz Kıyısında',
                'author' => 'Isabel Allende',
                'description' => 'Deniz Kıyısında, aşk, kayıp ve keşif temaları etrafında gelişen, büyüleyici bir roman.',
                'isbn_number' => '978-006-059-536-2',
                'number_of_pages' => 400,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'book_name' => 'Zamanın Efendisi',
                'author' => 'H.G. Wells',
                'description' => 'Zamanın Efendisi, zaman yolculuğu ve gelecekteki toplumlar üzerine düşündüren, klasik bir bilim kurgu eseri.',
                'isbn_number' => '978-006-059-536-2',
                'number_of_pages' => 200,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'book_name' => 'Karanlık Bir Yerde',
                'author' => 'Ruth Ware',
                'description' => 'Karanlık Bir Yerde, gizem ve gerilimi harmanlayan, okuyucuyu şaşırtan bir cinayet romanı.',
                'isbn_number' => '978-006-059-536-2',
                'number_of_pages' => 368,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'book_name' => 'Bir Anı Daha',
                'author' => 'Nina George',
                'description' => 'Bir Anı Daha, geçmişin ve hatıraların etkisiyle yüzleşen bir kadının dokunaklı yolculuğunu anlatır.',
                'isbn_number' => '978-006-059-536-2',
                'number_of_pages' => 330,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'book_name' => 'Aşkın Anı',
                'author' => 'Sarah Jio',
                'description' => 'Aşkın Anı, geçmiş ve gelecekteki aşk öykülerini birbirine bağlayan, etkileyici bir roman.',
                'isbn_number' => '978-006-059-536-2',
                'number_of_pages' => 300,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'book_name' => 'Gölgeler Ülkesi',
                'author' => 'Ursula K. Le Guin',
                'description' => 'Gölgeler Ülkesi, fantastik bir dünyada geçen ve sosyal temaları işleyen bir hikaye.',
                'isbn_number' => '978-006-059-536-2',
                'number_of_pages' => 280,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'book_name' => 'Sonsuz Gece',
                'author' => 'Tariq Ali',
                'description' => 'Sonsuz Gece, tarih ve kültür temalarını ele alan derin ve sürükleyici bir anlatım.',
                'isbn_number' => '978-006-059-536-2',
                'number_of_pages' => 310,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
